# NumPy Assignment

In [32]:
import numpy as np


## 1. 1D array (1 to 20)

Basic stats first, then find where values are > 10.


In [33]:
# numbers 1 through 20
arr = np.arange(1, 21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [34]:
print("sum:", arr.sum())
print("mean:", arr.mean())
print("median:", np.median(arr))
print("std:", arr.std())


sum: 210
mean: 10.5
median: 10.5
std: 5.766281297335398


In [35]:
# positions where value > 10 (not the values themselves)
idx = np.where(arr > 10)
print(idx)


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


## 2. 4x4 array

Make it, transpose it, then sum by rows and columns.


In [36]:
arr2d = np.arange(1, 17).reshape(4, 4)
print(arr2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [37]:
# rows <-> columns
print(arr2d.T)


[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [38]:
# axis=1 → across each row, axis=0 → down each column
print("row sums:", np.sum(arr2d, axis=1))
print("col sums:", np.sum(arr2d, axis=0))


row sums: [10 26 42 58]
col sums: [28 32 36 40]


## 3. Two random 3x3 arrays

Element-wise ops, then a proper matrix multiply (dot).


In [39]:
# random ints from 1 to 20
a = np.random.randint(1, 21, size=(3, 3))
b = np.random.randint(1, 21, size=(3, 3))
print("a:\n", a)
print("b:\n", b)


a:
 [[13  3 14]
 [16 15  8]
 [ 9  4 12]]
b:
 [[ 2  2 15]
 [ 3 16 12]
 [14 10  7]]


In [40]:
print("add:\n", a + b)
print("sub:\n", a - b)
print("mul:\n", a * b) 


add:
 [[15  5 29]
 [19 31 20]
 [23 14 19]]
sub:
 [[11  1 -1]
 [13 -1 -4]
 [-5 -6  5]]
mul:
 [[ 26   6 210]
 [ 48 240  96]
 [126  40  84]]


In [41]:
print("dot product:\n", np.dot(a, b))


dot product:
 [[231 214 329]
 [189 352 476]
 [198 202 267]]


## 4. Reshape + slice

12 numbers → 3x4, then grab first 2 rows and last 2 cols.


In [42]:
flat = np.arange(1, 13)
mat = flat.reshape(3, 4)
print(mat)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
# [:2] = first two rows, [-2:] = last two columns
print(mat[:2, -2:])


[[3 4]
 [7 8]]
