In [1]:
import numpy as np 

# Task 1: Creating NumPy Arrays
1. Import NumPy as np.
2. Create the following arrays:
   - A 1D array of integers from 1 to 10
   - A 2D array of shape (3, 3) with values from 1 to 9
   - A NumPy array from the list: [10, 20, 30, 40]
3. Print:
   - Shape of each array
   - Data type of each array

In [4]:
arr_1d = np.arange(1, 11, 1)
print(arr_1d)
print("Shape of arr_1d:", arr_1d.shape)
print("Data type of arr_1d:", arr_1d.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
Shape of arr_1d: (10,)
Data type of arr_1d: int64


In [5]:
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)
print("Shape of arr_2d:", arr_2d.shape)
print("Data type of arr_2d:", arr_2d.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of arr_2d: (3, 3)
Data type of arr_2d: int64


In [6]:
lst = [10, 20, 30, 40]
arr_lst = np.array(lst)
print(arr_lst)
print("Shape of arr_lst:", arr_lst.shape)
print("Data type of arr_lst:", arr_lst.dtype)


[10 20 30 40]
Shape of arr_lst: (4,)
Data type of arr_lst: int64


# Task 2: Important Mathematical Operations
Given two arrays:
   ```
   A = np.array([10, 20, 30, 40])
   B = np.array([1, 2, 3, 4])
   ```
Perform and print results for:
1. Addition (A + B)
2. Subtraction (A - B)
3. Multiplication (A * B)
4. Division (A / B)
5. Power (A ** 2)

- Extra (optional): Use NumPy's functions: np.add(), np.subtract() for the same operations.

In [10]:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])

print(f"A + B : {A+B}")
print(f"A - B : {A-B}")
print(f"A * B : {A*B}")
print(f"A / B : {A/B}")
print(f"A**2 : {A**2}")

print("--------------------------------")

print(f"A + B : {np.add(A,B)}")
print(f"A - B : {np.subtract(A,B)}")
print(f"A * B : {np.multiply(A,B)}")
print(f"A / B : {np.divide(A,B)}")
print(f"A**2 : {np.power(A,2)}")

A + B : [11 22 33 44]
A - B : [ 9 18 27 36]
A * B : [ 10  40  90 160]
A / B : [10. 10. 10. 10.]
A**2 : [ 100  400  900 1600]
--------------------------------
A + B : [11 22 33 44]
A - B : [ 9 18 27 36]
A * B : [ 10  40  90 160]
A / B : [10. 10. 10. 10.]
A**2 : [ 100  400  900 1600]


# Task 3: Important NumPy Mathematical Formulas
Given:
```
values = np.array([2, 4, 6, 8, 10])
```
Calculate:
1. Square root of each element
2. Exponential of each element
3. Natural logarithm of each element
4. Sum of all elements
5. Cumulative sum of elements
- Use NumPy functions only.

In [11]:
values = np.array([2, 4, 6, 8, 10])

print(f"Square root of each element: {np.sqrt(values)}")
print(f"Exponential of each element: {np.exp(values)}")
print(f"Natural logarithm of each element: {np.log(values)}")
print(f"Sum of all elements: {np.sum(values)}")
print(f"Cumulative sum of elements: {np.cumsum(values)}")

Square root of each element: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential of each element: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural logarithm of each element: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum of all elements: 30
Cumulative sum of elements: [ 2  6 12 20 30]


# Task 4: Aggregation Operations
Given a 2D array:
```
data = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])
```
Find:
1. Row-wise sum
2. Column-wise sum
3. Minimum value
4. Maximum value
5. Overall mean


In [13]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("row wise sum: ", np.sum(data, axis=1))
print("column wise sum: ", np.sum(data, axis=0))
print("minimum value: ", np.min(data))
print("maximum value: ", np.max(data))
print("overall mean: ", np.mean(data))

row wise sum:  [ 60 150 240]
column wise sum:  [120 150 180]
minimum value:  10
maximum value:  90
overall mean:  50.0


# Task 5: Statistical Operations (Core Focus)
Given:
```
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
```
Calculate and print:
1. Mean
2. Median
3. Variance
4. Standard Deviation
5. Minimum & Maximum
6. Range (max - min)


In [14]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
print("mean: ", np.mean(marks))
print("median: ", np.median(marks))
print("variance: ", np.var(marks))
print("standard deviation: ", np.std(marks))
print("minimum: ", np.min(marks))
print("maximum: ", np.max(marks))
print("range: ", np.max(marks) - np.min(marks))

mean:  79.25
median:  81.5
variance:  134.1875
standard deviation:  11.583932838203095
minimum:  60
maximum:  95
range:  35


# Task 6: Percentiles & Sorting
Using the same marks array:
1. Sort the array
2. Find:
   - 25th percentile
   - 50th percentile
   - 75th percentile
3. Count how many students scored above the average marks

In [16]:
print(marks)
print("sorted marks: ", np.sort(marks))
print("25th percentile: ", np.percentile(marks, 25))
print("50th percentile: ", np.percentile(marks, 50))
print("75th percentile: ", np.percentile(marks, 75))

students_scored_above_average = marks > np.mean(marks)
print("students scored above the average marks: ", students_scored_above_average)
print("number of students scored above the average marks: ", np.sum(students_scored_above_average))


[78 85 90 66 72 88 95 60]
sorted marks:  [60 66 72 78 85 88 90 95]
25th percentile:  70.5
50th percentile:  81.5
75th percentile:  88.5
students scored above the average marks:  [False  True  True False False  True  True False]
number of students scored above the average marks:  4


# Task 7: Mini Use Case: Sales Analysis
Given daily sales data:
```
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
```
Perform:
1. Total weekly sales
2. Average daily sales
3. Highest and lowest sales day
4. Standard deviation of sales
5. Identify days where sales were above average

In [17]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

print("total weekly sales: ", np.sum(sales))
print("average daily sales: ", np.mean(sales))
print("highest sales day: ", np.max(sales))
print("lowest sales day: ", np.min(sales))
print("standard deviation of sales: ", np.std(sales))

sales_above_average = sales > np.mean(sales)
print("days where sales were above average: ", sales_above_average)

total weekly sales:  10700
average daily sales:  1528.5714285714287
highest sales day:  2000
lowest sales day:  900
standard deviation of sales:  345.2298849598449
days where sales were above average:  [False False False  True  True  True  True]
